-- AlterTable
ALTER TABLE "Loan" ADD COLUMN "termMonths" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Loan" ADD COLUMN "dueAt" DATETIME;
ALTER TABLE "Loan" ADD COLUMN "outstandingInterest" DECIMAL NOT NULL DEFAULT 0;
ALTER TABLE "Loan" ADD COLUMN "outstandingPenalty" DECIMAL NOT NULL DEFAULT 0;
